### ISSUE TITLE
the chat does not scroll

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/BrainBox#3]

**Comment by r03ert0** [comment]
now it does

**Comment by amyleerobinson** [comment]
awesome!

On Tue, Mar 8, 2016 at 7:43 PM, Roberto Toro <notifications@github.com>
wrote:

> now it does
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r03ert0/BrainBox/issues/3#issuecomment-194040581>.
>



-- 
Director, EyeWire <http://eyewire.org/>
@amyleerobinson <https://twitter.com/amyleerobinson>
